openapi: 3.0.0
info:
  version: 1.0.0
  title: Toko Komputer
  license:
    name: MIT
servers:
  - url: http://localhost/restapi/api
paths:
  /api.php:
    get:
      summary: List semua produk toko komputer
      operationId: listProduk
      tags:
        - produk

      responses:
        '200':
          description: Array dari data produk
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produks'
        default:
          description: Kesalahan tak terduga
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - produk
      summary: Memperbarui produk yang ada
      description: Memperbarui produk yang ada dengan Id
      operationId: updateProduk
      requestBody:
        description: Memperbarui produk yang ada
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produk'
          application/xml:
            schema:
              $ref: '#/components/schemas/Produk'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Produk'
        required: true
      responses:
        '200':
          description: Operasi sukses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sukses'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Sukses'
        '400':
          description: ID yang diberikan tidak valid
        '404':
          description: Produk tidak ditemukan
        '422':
          description: Pengecualian validasi
    post:
      tags:
        - produk
      summary: Tambahkan produk
      description: Tambahkan produk
      operationId: AddProduk
      requestBody:
        description: Buat produk
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produk'
          application/xml:
            schema:
              $ref: '#/components/schemas/Produk'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Produk'
        required: true
      responses:
        '200':
          description: Operasi sukses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sukses'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Sukses'
        '400':
          description: ID yang diberikan tidak valid
        '404':
          description: Produk tidak ditemukan
        '422':
          description: Pengecualian validasi     
    delete:
      tags:
        - produk
      summary: Hapus produk yang ada
      description: Hapus Produk yang ada dengan Id
      operationId: deleteProduk
      parameters:
        - name: id
          in: query
          description: Produk id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operasi sukses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sukses'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Sukses'
        '400':
          description: ID yang diberikan tidak valid
        '404':
          description: Produk tidak ditemukan
components:
  schemas:
    Produks:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Produk'
    Produk:
      type: object
      required:
        - id
        - nama
        - harga
        - promo
      properties:
        id:
          type: integer
          format: int64
        nama:
          type: string
        harga:
          type: integer
          format: int64
        promo:
          type: integer
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Sukses:
      type: object
      required:
        - message
      properties:
        message:
          type: string